### ISSUE TITLE
feature request: --format 

### ISSUE THREAD

**Issue by neeasade** [Wildefyr/mpvc#1]
Just to put it on the radar, would be nice to have an equivalent to mpc --format with relevant options.

nice script :)

**Comment by Wildefyr** [comment]
I'm not familiar with this option, can you give me an example?

**Comment by neeasade** [comment]
Currently away from comp, here's the snippet from the man page:
```
-f,--format

Configure the format of song display for status and the playlist. The metadata delimiters are "%name%", "%artist%", "%album%", "%title%", "%track%", "%time%", and "%file%". The [] operator is used to group output such that if no metadata delimiters are found or matched between '[' and ']', then none of the characters between '[' and ']' are output. '&' and '|' are logical operators for and and or. '#' is used to escape characters. Some useful examples for format are: "%file%" and "[[%artist% - ]%title%]|[%file%]". This command also takes the following defined escape sequences:
\\ - backslash
\a - alert
\b - backspace
\t - tab
\n - newline
\v - vertical tab
\f - form-feed
\r - carriage return
```

eg `mpc --format "%file%"`would give just the filename.

upon rethinking there might not be a lot of options/use for this here -- mainly I just wanted a way to get title only without `mpvc | head -n 1`.

**Comment by Wildefyr** [comment]
No I ![certainly agree](https://u.teknik.io/YKWDZA.png) some kind of formatting is needed. The question is how. Thankfully using printf we can have support for escape sequences, but not sure how to implement `[]` and the logical operators. Probably going to have to adapt the getopts method too as that only returns the next argument... Also how to implement the formatting arguments themshelves such as `%artist%`. More thought is needed before I try implementing this.

**Comment by Wildefyr** [comment]
f41fe821c9e7c593d83b45d5af48695a9d676d94 implements this. Next please!

**Comment by neeasade** [comment]
thanks!
