### ISSUE TITLE
Build phraser to set absolute time of track with timestamp format.

### ISSUE THREAD

**Issue by wildefyr** [wildefyr/mpvc#10]

**Comment by heckendorfc** [comment]
Is c309e8a sufficient?

**Comment by wildefyr** [comment]
I think so, perhaps validate that the user has entered two digits when referring to minutes and seconds however? I'm not massively bothered but I think it would be nice.

**Comment by heckendorfc** [comment]
Committed 6e23261 with some validation. Feel free to reword/reformat the error message but is this close to what you had in mind?

**Comment by wildefyr** [comment]
That regex doesn't quite work if you use the '+' symbol in front of the signal digit value like this:

`mpvc -t +1m`

**Comment by heckendorfc** [comment]
I didn't think that was a valid syntax. Sign characters should be stripped out by setTimeRelative before passing them to parseTimeString anyway. Updated in cbc8e46.

**Comment by wildefyr** [comment]
No it wasn't really, the parser just 'ignored' it. Anyway, I think this is finished! Great moves, proud of you!
