### ISSUE TITLE
formatPrint sed replacement error

### ISSUE THREAD

**Issue by heckendorfc** [wildefyr/mpvc#17]
If the file metadata contains '&', the %tag% will be inserted back like:
`echo 'one %two% three' | sed 's#%two%#four&five#g'`
would return:
'one four%two%five three' rather than 'one four&five three'

'&' will fix that behaviour but I'm not sure of an easy way to do that.

**Comment by wildefyr** [comment]
Fixed in 41d3d63

**Comment by heckendorfc** [comment]
What if the metadata or -f argument contains two '%' characters apart from one of the replacement tags? ;)

`echo 'one %two% three' | sed 's#%two%#30% & 70%#g' | sed 's#%.*%#\&#'`
"one 30& three", instead of "one 30% & 70% three"

**Comment by heckendorfc** [comment]
I reverted your fix and committed efa0444 which escapes the & in getMetadata before it gets to sed. I don't think there's any way to recover after sed ruins the input.

\1 is another similar kind of problem but I think it will be less common and slightly harder to fix.
