### ISSUE TITLE
--input-unix-socket is being replaced with --input-ipc-server

### ISSUE THREAD

**Issue by wildefyr** [wildefyr/mpvc#18]
But `--input-ipc-server` is still very new, having only been added last mpv release, breaking compatibility with older mpv versions. I think the best solution will be to wait until mpv git removes `--input-unix-socket` completely, then start using and recommending it.

**Comment by heckendorfc** [comment]
I agree.

**Comment by z1lt0id** [comment]
With the latest mpv git --input-unix-socket has been removed.

**Comment by z1lt0id** [comment]
For example I get this error msg since the latest mpv git update.
```
./mpvc -a /srv/nas/thevault/tv/Supernatural/Season\ 06/Supernatural.S06E21.Bluray-1080p-Sonarr.mkv 
Adding: Supernatural.S06E21.Bluray-1080p-Sonarr.mkv
/tmp/mpvsocket is not currently open or has been corrupted.
```

**Comment by wildefyr** [comment]
Thanks for the heads up, time to figure out what they're replacing it with and how.

**Comment by wildefyr** [comment]
Can anyone test that replacing --input-unix-socket with --input-ipc-server leads to no ill effects? If so I will update.

**Comment by heckendorfc** [comment]
--input-ipc-server works fine with newer mpv (tested 0.22.0), but it should break on anything older than 0.17.0. The latest broken version, 0.16.0, was released nearly a year ago. Time for 0.16.0 users to update.

**Comment by wildefyr** [comment]
Agreed, fixed in 864d1f0.

**Comment by z1lt0id** [comment]
Glad to see it resolved.  Will try it out shortly :)

**Comment by EternityForest** [comment]
I know this is a resolved issue, but I'm commenting anyway because I've noticed several breaking changes like this(Starting with the old --nogui option from mplayer which cost me almost a whole day to figure out why a library couldn't call mplayer)

 Is there any significant performance impact at all to just keeping both versions? Isn't backwards compatibility pretty critical to any API?

**Comment by lwilletts** [comment]
Probably not, I don't know why they decided to update it @EternityForest. I've started work back up on this now so any lingering issues feel free to contact me.
