### ISSUE TITLE
Phraser cannot handle files with spaces in them.

### ISSUE THREAD

**Issue by heckendorfc** [wildefyr/mpvc#19]
Is it worth mentioning that `mpvc -a $(find . -type f)` will not work if the filenames have spaces? To use find this way you would need to use `find . -type f -print0 | xargs -0 mpvc -a` but at that point you might as well just pipe directly to mpvc. Nothing is really gained by using the command line argument syntax here.

`mpvc -a *` will still work fine however.

**Comment by wildefyr** [comment]
I agree, I'll add it to the readme in a second.

**Comment by wildefyr** [comment]
Updated: I've just mentioned that it won't work in subshells and recommend using find first.
